task:
  matrix:
    - name: FreeBSD -- gcc | g++
      freebsd_instance:
        image: freebsd-13-1-release-amd64
      env:
        cc: gcc
        cxx: g++
    - name: MacOS M1 -- gcc | g++
      macos_instance:
        image: ghcr.io/cirruslabs/macos-monterey-base:latest
      env:
        cc: gcc
        cxx: g++
  dependencies_script: |
    echo $(uname)
    if [ "$(uname)" = "FreeBSD" ]; then
      pkg install -y cmake bash
    else
      brew install cmake
    fi
  configure_script: |
    mkdir instdir
    mkdir build
    cd build
    cmake \
      -DCMAKE_C_COMPILER=$cc \
      -DCMAKE_CXX_COMPILER=$cxx \
      -DTEST_OPENMP=OFF \
      -DBUILD_INTERFACE_C=ON \
      -DBUILD_TESTS=ON \
      -DCMAKE_INSTALL_PREFIX=../instdir \
      ..
  build_script: |
    cmake --build build --parallel 8 --config Release
  install_script: |
    cmake --install build --config Release
  test_script: |
    export PATH=`pwd`/build/bin:$PATH
    echo $PATH
    if [ "$(uname)" = "FreeBSD" ]; then
      ln -s /usr/local/bin/bash /bin/bash
    fi
    cd build
    ctest -C Release --parallel 8
